homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }
    methods: [GET]

tasklist:
    path:      /tasklist
    defaults:  { _controller: AppBundle:Default:taskList }
    methods: [GET]