project:
    path:      /list
    defaults:  { _controller: ProjectBundle:Default:projectList }
    methods: [GET]

project_add:
    path: /add
    defaults:   { _controller: ProjectBundle:Default:add}